// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Directory struct {
	ID   int64
	Path string
}

type Tag struct {
	ID   int64
	Name string
}

type Video struct {
	ID            int64
	Filename      string
	DirectoryID   sql.NullInt64
	DirectoryPath string
	DisplayName   string
	ShowName      string
	ThumbnailPath string
}

type VideoTag struct {
	VideoID int64
	TagID   int64
}
