// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Directory struct {
	ID   int64
	Path string
}

type Tag struct {
	ID   int64
	Name string
}

type Video struct {
	ID          int64
	Filename    string
	DirectoryID int64
	DisplayName string
}

type VideoTag struct {
	VideoID int64
	TagID   int64
}
